# ── AI AGENT DIRECTORY ──
AGENTS_DIRECTORY = {
    "Coding Agents": [
        {"name": "Cursor", "desc": "VS Code fork. Composer mode for multi-file edits. Claude Sonnet 5, GPT-5, Gemini 3.1.", "url": "https://cursor.com", "price": "Free / $20/mo", "type": "IDE"},
        {"name": "Claude Code", "desc": "Anthropic CLI. 80.9% SWE-bench. Agent Teams feature for parallel coding.", "url": "https://docs.anthropic.com/en/docs/claude-code", "price": "$20/mo+ API", "type": "CLI"},
        {"name": "GitHub Copilot", "desc": "Agent Mode in VS Code. Issue-to-PR. Multi-model (Claude, GPT-5.4, Gemini 3.1).", "url": "https://github.com/features/copilot", "price": "$10/mo / $39/mo Pro+", "type": "IDE"},
        {"name": "Devin", "desc": "Cognition's fully autonomous SWE. Sandboxed cloud env. Interactive Planning.", "url": "https://devin.ai", "price": "$20/mo + ACU", "type": "Autonomous"},
        {"name": "Windsurf", "desc": "Cascade agentic mode. Project-level memory. 5 parallel agents.", "url": "https://windsurf.com", "price": "Free / $15/mo", "type": "IDE"},
        {"name": "Aider", "desc": "OSS pair programmer. Git-aware. Works with any LLM.", "url": "https://github.com/paul-gauthier/aider", "price": "Free + API", "type": "CLI"},
        {"name": "OpenHands", "desc": "OSS autonomous software engineer (ex-OpenDevin).", "url": "https://github.com/All-Hands-AI/OpenHands", "price": "Free (OSS)", "type": "Autonomous"},
        {"name": "Bolt.new", "desc": "Prompt to full-stack web app in the browser. StackBlitz.", "url": "https://bolt.new", "price": "Free / Paid", "type": "App Builder"},
        {"name": "Lovable", "desc": "Describe → build → deploy from chat. No-code web apps.", "url": "https://lovable.dev", "price": "Free / $20/mo", "type": "App Builder"},
        {"name": "v0 (Vercel)", "desc": "Prompt to React/Tailwind components. Shadcn/ui integration.", "url": "https://v0.dev", "price": "Free / Pro", "type": "App Builder"},
        {"name": "Gemini CLI", "desc": "Google's official OSS terminal agent. ReAct loop. MCP support. 1M context.", "url": "https://github.com/google-gemini/gemini-cli", "price": "Free", "type": "CLI"},
        {"name": "Cline", "desc": "VS Code extension. Full terminal + browser access for Claude/GPT.", "url": "https://github.com/cline/cline", "price": "Free + API", "type": "IDE"},
    ],
    "Agent Frameworks": [
        {"name": "LangChain", "desc": "Most adopted framework. Modular architecture, memory, tools, chains.", "url": "https://github.com/langchain-ai/langchain", "price": "Free (OSS)", "type": "General"},
        {"name": "LangGraph", "desc": "Graph-based agent orchestration. Stateful directed graphs with cycles.", "url": "https://github.com/langchain-ai/langgraph", "price": "Free (OSS)", "type": "Orchestration"},
        {"name": "CrewAI", "desc": "Role-based crew members with goals and tools. Used by 60%+ Fortune 500.", "url": "https://github.com/crewAIInc/crewAI", "price": "Free (OSS)", "type": "Multi-Agent"},
        {"name": "AutoGen", "desc": "Microsoft multi-agent conversations. Flexible, event-driven.", "url": "https://github.com/microsoft/autogen", "price": "Free (OSS)", "type": "Multi-Agent"},
        {"name": "MetaGPT", "desc": "PM → Architect → Engineer roles. Software company simulation. 58.8k stars.", "url": "https://github.com/geekan/MetaGPT", "price": "Free (OSS)", "type": "Multi-Agent"},
        {"name": "DSPy", "desc": "Stanford. Programming not prompting. Auto-optimizes your pipeline.", "url": "https://github.com/stanfordnlp/dspy", "price": "Free (OSS)", "type": "General"},
        {"name": "OpenAI Agents SDK", "desc": "Official multi-step agents with handoffs. Python.", "url": "https://github.com/openai/openai-agents-python", "price": "Free (OSS)", "type": "General"},
        {"name": "Smolagents", "desc": "HuggingFace. Minimal agents in ~1000 lines. Model-agnostic.", "url": "https://github.com/huggingface/smolagents", "price": "Free (OSS)", "type": "Lightweight"},
        {"name": "Pydantic AI", "desc": "Type-safe. Clean Pythonic API. Production-ready agent framework.", "url": "https://github.com/pydantic/pydantic-ai", "price": "Free (OSS)", "type": "General"},
        {"name": "LlamaIndex", "desc": "Data-focused framework. Best-in-class for RAG agents.", "url": "https://github.com/run-llama/llama_index", "price": "Free (OSS)", "type": "RAG"},
        {"name": "Google ADK", "desc": "Google's Agent Development Kit. Native Gemini. Multi-agent orchestration.", "url": "https://github.com/google/adk-python", "price": "Free (OSS)", "type": "General"},
        {"name": "OpenClaw", "desc": "Fastest-growing GitHub repo. Self-hosted across WhatsApp, Telegram, Discord.", "url": "https://github.com/openclaw/openclaw", "price": "Free (OSS)", "type": "Platform"},
    ],
    "Browser & Desktop Agents": [
        {"name": "OpenAI Operator", "desc": "ChatGPT autonomous web agent. Human checkpoints. CUA technology.", "url": "https://operator.chatgpt.com", "price": "ChatGPT Pro", "type": "Browser"},
        {"name": "Manus (Meta)", "desc": "Autonomous digital employee. Meta-acquired. Browser Operator extension.", "url": "https://manus.im", "price": "Free / Paid", "type": "Browser"},
        {"name": "Claude Computer Use", "desc": "Anthropic desktop/browser control via screenshots. API access.", "url": "https://docs.anthropic.com/en/docs/agents-and-tools/computer-use", "price": "API", "type": "Desktop"},
        {"name": "Browser Use", "desc": "OSS browser agent library. Used by Manus. Python-native.", "url": "https://github.com/browser-use/browser-use", "price": "Free (OSS)", "type": "Infra"},
        {"name": "Google Mariner", "desc": "Gemini browser agent. Multi-tasking in Chrome. Waitlist.", "url": "https://deepmind.google/technologies/project-mariner/", "price": "Waitlist", "type": "Browser"},
        {"name": "Skyvern", "desc": "Vision-driven browsing. No coded selectors. GPT-4V navigation.", "url": "https://github.com/Skyvern-AI/skyvern", "price": "Free (OSS)", "type": "Infra"},
    ],
    "Voice Agents": [
        {"name": "ElevenLabs", "desc": "Industry-leading voice synthesis. Voice agents, dubbing, sound effects.", "url": "https://elevenlabs.io", "price": "Free / $5/mo+", "type": "Platform"},
        {"name": "PlayAI", "desc": "Voice agents for calls. 2x faster than real-time. Natural conversations.", "url": "https://play.ai", "price": "Free / Paid", "type": "Platform"},
        {"name": "Retell AI", "desc": "Voice AI for phone calls. Low latency. Custom voices.", "url": "https://retell.ai", "price": "Free / Paid", "type": "Platform"},
        {"name": "Vocode", "desc": "OSS library for building voice agents. Twilio integration.", "url": "https://github.com/vocode/vocode", "price": "Free (OSS)", "type": "Framework"},
        {"name": "Bland AI", "desc": "Enterprise call automation. Handle millions of conversations.", "url": "https://bland.ai", "price": "Enterprise", "type": "Platform"},
    ],
    "CRM & Sales Agents": [
        {"name": "Clay", "desc": "AI data enrichment. Personalized outreach at scale.", "url": "https://clay.com", "price": "From $149/mo", "type": "Sales"},
        {"name": "Apollo.io", "desc": "AI prospecting, sequences, scoring. 275M+ contacts database.", "url": "https://apollo.io", "price": "Free / $49+/mo", "type": "Sales"},
        {"name": "Intercom Fin", "desc": "AI support agent. Resolves 50%+ tickets autonomously.", "url": "https://intercom.com", "price": "From $29/seat", "type": "Support"},
        {"name": "HubSpot Breeze", "desc": "Copilot, agents, intelligence. Agent marketplace included.", "url": "https://hubspot.com", "price": "Free / $45+/mo", "type": "CRM"},
        {"name": "Instantly", "desc": "AI cold email. Unlimited accounts. Smart rotation.", "url": "https://instantly.ai", "price": "From $30/mo", "type": "Sales"},
        {"name": "Ada", "desc": "Autonomous support. Multi-channel. SOP Playbooks.", "url": "https://ada.cx", "price": "Enterprise", "type": "Support"},
    ],
    "Data & Research Agents": [
        {"name": "Claude Deep Research", "desc": "Multi-step investigation with citations. Sonnet 5 / Opus 4.6.", "url": "https://claude.ai", "price": "Claude Pro", "type": "Research"},
        {"name": "ChatGPT Deep Research", "desc": "Extended reasoning, web browsing, reports. GPT-5.4.", "url": "https://chat.openai.com", "price": "ChatGPT Pro", "type": "Research"},
        {"name": "GPT Researcher", "desc": "OSS autonomous comprehensive research agent.", "url": "https://github.com/assafelovic/gpt-researcher", "price": "Free (OSS)", "type": "Research"},
        {"name": "Julius AI", "desc": "Upload CSV/Excel. Ask questions in natural language.", "url": "https://julius.ai", "price": "Free / Paid", "type": "Data"},
        {"name": "PandasAI", "desc": "Chat with your data. NL queries to Pandas/SQL.", "url": "https://github.com/Sinaptik-AI/pandas-ai", "price": "Free (OSS)", "type": "Data"},
    ],
    "Self-Hosted & Local": [
        {"name": "Ollama", "desc": "Run LLMs locally. Dead simple CLI. 162k+ stars. All major models.", "url": "https://github.com/ollama/ollama", "price": "Free (OSS)", "type": "Runner"},
        {"name": "Open WebUI", "desc": "Self-hosted ChatGPT UI. Access control. Extensions.", "url": "https://github.com/open-webui/open-webui", "price": "Free (OSS)", "type": "UI"},
        {"name": "LM Studio", "desc": "Desktop app for local LLMs. Beautiful UI. All platforms.", "url": "https://lmstudio.ai", "price": "Free", "type": "Desktop"},
        {"name": "Anything LLM", "desc": "All-in-one AI app. RAG, agents, workspaces. Desktop + Docker.", "url": "https://github.com/Mintplex-Labs/anything-llm", "price": "Free (OSS)", "type": "Platform"},
        {"name": "LLamaFile", "desc": "LLMs as single executable files. Zero setup. Mozilla.", "url": "https://github.com/Mozilla-Ocho/llamafile", "price": "Free (OSS)", "type": "Runner"},
    ],
    "Platforms & Hubs": [
        {"name": "ChatGPT", "desc": "GPTs, Deep Research, Canvas, Agent Mode, vision, voice. GPT-5.4.", "url": "https://chat.openai.com", "price": "Free / $20+/mo", "type": "Platform"},
        {"name": "Claude", "desc": "Tool use, MCP, computer control, Chrome, Cowork. Sonnet 5 / Opus 4.6.", "url": "https://claude.ai", "price": "Free / $20+/mo", "type": "Platform"},
        {"name": "Gemini", "desc": "Deep Think, Gems, 1M context, multi-modal. Gemini 3.1 Pro.", "url": "https://gemini.google.com", "price": "Free / $19.99+/mo", "type": "Platform"},
        {"name": "Grok", "desc": "Real-time X data. Multi-agent Society of Mind. Grok 4.20.", "url": "https://x.ai", "price": "X Premium+", "type": "Platform"},
        {"name": "Coze", "desc": "ByteDance agent builder. Visual workflow. Plugin marketplace.", "url": "https://coze.com", "price": "Free / Paid", "type": "Platform"},
    ],
}
