import hashlib
from flask import send_file

# ── PDF GENERATOR FOR AI AGENT DIRECTORY ──
import os as _os, datetime as _dt

PDF_CACHE_PATH = _os.path.join(_os.path.dirname(__file__), 'static', 'agents-directory-2026.pdf')

def _generate_directory_pdf():
    """Generate a beautiful PDF of the AI Agent Directory using weasyprint."""
    cat_icons = {
        'Coding Agents': '🖥️', 'Agent Frameworks': '🧱',
        'Browser & Desktop Agents': '🌐', 'Voice Agents': '🎤',
        'CRM & Sales Agents': '💼', 'Data & Research Agents': '📊',
        'Self-Hosted & Local': '🏠', 'Platforms & Hubs': '🤖'
    }
    
    total = sum(len(agents) for agents in AGENTS_DIRECTORY.values())
    now = _dt.datetime.now().strftime('%B %d, %Y')
    
    # Build table rows
    table_rows = ''
    for cat, agents in AGENTS_DIRECTORY.items():
        table_rows += f'<tr class="cat-header"><td colspan="4">{cat_icons.get(cat, "📦")} {cat} ({len(agents)})</td></tr>'
        for a in agents:
            table_rows += f'<tr><td class="name">{a["name"]}</td><td class="type">{a["type"]}</td><td class="price">{a["price"]}</td><td class="desc">{a["desc"][:100]}</td></tr>'
    
    html = f'''<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>AI Agent Directory 2026 — Complete Guide</title>
<style>
  @page {{ size: A4; margin: 1.5cm; }}
  @page {{ @top-center {{ content: "AI Agent Directory 2026"; font-size: 9pt; color: #888; }} }}
  @page {{ @bottom-center {{ content: "Page " counter(page) " of " counter(pages); font-size: 8pt; color: #888; }} }}
  * {{ font-family: -apple-system, 'Segoe UI', Roboto, sans-serif; }}
  body {{ color: #1a1a2e; font-size: 10pt; line-height: 1.5; }}
  
  .cover {{
    text-align: center;
    padding: 60px 0 40px;
    border-bottom: 4px solid #7c3aed;
    margin-bottom: 30px;
  }}
  .cover h1 {{ font-size: 28pt; font-weight: 800; margin: 0 0 8px; background: linear-gradient(135deg, #7c3aed, #ec4899); -webkit-background-clip: text; -webkit-text-fill-color: transparent; }}
  .cover .sub {{ font-size: 14pt; color: #666; }}
  .cover .meta {{ font-size: 9pt; color: #999; margin-top: 20px; }}
  
  .section-title {{ font-size: 14pt; font-weight: 700; color: #7c3aed; margin: 25px 0 10px; padding-bottom: 5px; border-bottom: 2px solid #7c3aed20; }}
  
  table {{ width: 100%; border-collapse: collapse; margin: 5px 0 20px; font-size: 9pt; }}
  th {{ background: #7c3aed; color: white; padding: 8px 10px; text-align: left; font-weight: 600; font-size: 8.5pt; text-transform: uppercase; letter-spacing: 0.5px; }}
  th:nth-child(1) {{ width: 22%; }}
  th:nth-child(2) {{ width: 12%; }}
  th:nth-child(3) {{ width: 18%; }}
  th:nth-child(4) {{ width: 48%; }}
  .cat-header td {{ background: #7c3aed15; color: #7c3aed; font-weight: 700; padding: 7px 10px; font-size: 10pt; }}
  td {{ padding: 5px 10px; border-bottom: 1px solid #e0dce8; vertical-align: top; }}
  tr:nth-child(even):not(.cat-header) td {{ background: #f8f6fc; }}
  .name {{ font-weight: 600; }}
  .type {{ color: #7c3aed; font-size: 8pt; }}
  .price {{ color: #2563eb; font-size: 8pt; }}
  .desc {{ color: #555; font-size: 8.5pt; }}
  
  .summary {{ margin-top: 30px; padding: 20px; background: #f8f6fc; border-radius: 8px; font-size: 9pt; }}
  .summary h3 {{ font-size: 11pt; color: #7c3aed; margin: 0 0 10px; }}
  
  .footer {{ margin-top: 40px; text-align: center; font-size: 8pt; color: #999; border-top: 1px solid #ddd; padding-top: 15px; }}
</style>
</head>
<body>

<div class="cover">
  <div style="font-size: 48pt; margin-bottom: 10px;">\U0001f916</div>
  <h1>AI Agent Directory 2026</h1>
  <div class="sub">The Complete Guide to 50+ AI Agents, Frameworks & Tools</div>
  <div class="meta">Compiled: {now} · {total} Entries · 8 Categories<br>Source: awesome-ai-agents-2026</div>
</div>

<div class="section-title">Full Directory</div>
<table>
  <tr><th>Agent</th><th>Type</th><th>Pricing</th><th>Description</th></tr>
  {table_rows}
</table>

<div class="summary">
  <h3>How to Use This Directory</h3>
  <p><strong>For Developers:</strong> Browse the Coding Agents and Frameworks sections to find the best tools for your stack. Top picks: Cursor (IDE), Claude Code (CLI), CrewAI (multi-agent orchestration).</p>
  <p><strong>For Businesses:</strong> CRM & Sales agents offer the fastest ROI. Apollo.io and Clay are industry standards for outbound. Intercom Fin for support automation.</p>
  <p><strong>For Builders:</strong> Combine Bolt.new or Lovable (prompt-to-app) with LangChain or AutoGen (agent framework) to ship AI products faster.</p>
  <p><strong>For Self-Hosters:</strong> Ollama + Open WebUI gives you a private ChatGPT. Add Anything LLM for RAG capabilities.</p>
</div>

<div class="footer">
  Generated by ShopZario.com · AI Agent Directory 2026 · Updated Quarterly
</div>

</body>
</html>'''
    
    try:
        from weasyprint import HTML
        HTML(string=html).write_pdf(PDF_CACHE_PATH)
        return True
    except Exception as e:
        print(f"[PDF] Error: {e}")
        return False

@app.route('/api/admin/generate-agents-pdf')
@admin_required
def api_generate_agents_pdf():
    """Generate the PDF cache."""
    ok = _generate_directory_pdf()
    if ok:
        size = _os.path.getsize(PDF_CACHE_PATH) if _os.path.exists(PDF_CACHE_PATH) else 0
        return jsonify({'success': True, 'path': '/static/agents-directory-2026.pdf', 'size': f'{size//1024}KB'})
    return jsonify({'error': 'PDF generation failed'}), 500

@app.route('/api/download/agents-pdf')
def api_download_agents_pdf():
    """Serve the PDF directly (free access for now, Stripe gating later)."""
    import os as _os2
    path = _os2.path.join(_os2.path.dirname(__file__), 'static', 'agents-directory-2026.pdf')
    if _os2.path.exists(path):
        return send_file(path, mimetype='application/pdf',
                      as_attachment=True, download_name='ai-agent-directory-2026.pdf')
    # Generate on demand
    _generate_directory_pdf()
    if _os2.path.exists(path):
        return send_file(path, mimetype='application/pdf',
                      as_attachment=True, download_name='ai-agent-directory-2026.pdf')
    return 'PDF generation in progress. Try again in a moment.', 202
