"""Product Experience Hub - generate complete function source."""
FUNC = []
FUNC.append('def product_detail_page(product_id):')
FUNC.append('    import json as _json, datetime as _dt')
FUNC.append('    db = get_db(); c = db.cursor()')
FUNC.append('    row = c.execute("SELECT * FROM products WHERE id=?", (product_id,)).fetchone()')
FUNC.append('    if not row:')
FUNC.append('        db.close()')
FUNC.append("        return (LAYOUT_HEAD + TOP_NAV + '<div class=\"max-w-4xl mx-auto px-4 py-20 text-center\"><div class=\"text-6xl mb-4 opacity-20\">&#x1f50d;</div><h1 class=\"text-2xl font-bold mb-2\">Not Found</h1><a href=\"/\" class=\"btn-primary\">Browse Marketplace</a></div>' + LAYOUT_FOOT, 404)")
FUNC.append('    p = dict(row); Q = chr(39)')
FUNC.append('    ptype = (p.get("product_type") or "other")')
FUNC.append('    icon = product_type_icon(ptype)')
FUNC.append('    color = product_type_color(ptype)')
FUNC.append('    label = PRODUCT_TYPE_LABELS.get(ptype, "Digital Product")')
FUNC.append('    t = (p.get("title") or "").strip()')
FUNC.append('    d = p.get("description") or ""')
FUNC.append('    pr = float(p.get("price", 0) or 0)')
FUNC.append('    rt = float(p.get("rating", 0) or 0)')
FUNC.append('    dl = int(p.get("downloads_count", 0) or 0)')
FUNC.append('    ver = p.get("version", "1.0") or "1.0"')
FUNC.append('    lt = (p.get("license") or "standard").lower()')
FUNC.append('    hero = p.get("hero_image_url") or ""')
FUNC.append('    slug = p.get("slug") or product_id')
FUNC.append('    seo_t = (p.get("seo_title") or t)[:68]')
FUNC.append('    seo_d = (p.get("seo_description") or d[:155])[:160]')
FUNC.append('    body = p.get("content") or p.get("features") or d')
FUNC.append('    reqs = p.get("requirements") or ""')
FUNC.append('    vid = p.get("video_url") or ""')
FUNC.append('    faq_raw = p.get("faq") or ""')
FUNC.append('    changelog = p.get("changelog") or ""')
FUNC.append('    creator = p.get("creator_name") or "AI Factory"')
FUNC.append('    now = _dt.datetime.now()')
FUNC.append('    sv = max(1, 50 - min(dl, 49))')
FUNC.append('    rvc = max(1, int(rt * 3 + 1))')
FUNC.append('    stars = ""')
FUNC.append('    for _ in range(int(rt)): stars += \'<i class="fas fa-star text-yellow-400"></i>\'')
FUNC.append("    if rt - int(rt) > 0.3: stars += '<i class=\"fas fa-star-half-alt text-yellow-400\"></i>'")
FUNC.append('    for _ in range(5 - int(rt) - (1 if rt - int(rt) > 0.3 else 0)): stars += \'<i class="far fa-star text-gray-700"></i>\'')
FUNC.append('    # Image')
FUNC.append("    img = '<div class=\"aspect-[4/3] rounded-2xl bg-gradient-to-br from-purple-900/30 to-black/40 border border-white/10 flex items-center justify-center\"><span class=\"text-7xl opacity-30\">' + icon + '</span></div>'")
FUNC.append('    if hero:')
FUNC.append("        img = '<div class=\"rounded-2xl overflow-hidden bg-black/40 border border-white/10 group\"><div class=\"aspect-[4/3]\"><img src=\"' + hero.replace('\"', '') + '\" alt=\"' + t.replace('\"', '')[:60] + '\" class=\"w-full h-full object-cover transition-transform duration-700 group-hover:scale-105 cursor-zoom-in\" onclick=\"window.open(this.src,' + Q + '_blank' + Q + ')\"></div></div>'")
FUNC.append('    # Specs')
FUNC.append("    fmap = {'prompt_pack': {'f':'PDF+TXT','d':'Beginner','c':'ChatGPT,Claude'}, 'template': {'f':'Canva+Slides','d':'Beginner','c':'Canva,GSuite'}, 'ebook': {'f':'PDF+EPUB+MOBI','d':'All','c':'Kindle,Apple'}, 'code': {'f':'ZIP','d':'Int-Adv','c':'VS Code,PyCharm'}, 'course': {'f':'MP4+PDF','d':'All','c':'Browser'}}")
FUNC.append('    fm = fmap.get(ptype, {}); fmt = fm.get("f","Digital"); diff = fm.get("d","All"); compat = fm.get("c","Browser,Desktop")')
FUNC.append('    inc_map = {"prompt_pack":["150+ prompts","Guide","Examples","Updates"],"template":["Editable files","Guide","Tutorial","Updates"],"ebook":["PDF+EPUB+MOBI","Workbook","Resources","Updates"],"code":["Scripts","Docs","Tests","Requirements"],"course":["HD video","Workbook","Certificate","Community"]}')
FUNC.append('    inc = inc_map.get(ptype, ["Digital files","Guide","Docs","Updates"])')
FUNC.append('    ih = "".join([\'<div class="flex items-start gap-3 p-3 bg-black/30 rounded-xl border border-white/10"><div class="w-6 h-6 rounded-full bg-green-500/10 flex items-center justify-center shrink-0"><i class="fas fa-check text-green-400 text-[10px]"></i></div><span class="text-xs font-medium text-white">\' + x + \'</span></div>\' for x in inc])')
FUNC.append('    sp = [("Type",label,icon),("Format",fmt,"fa-file"),("Level",diff,"fa-signal"),("Version",ver,"fa-code-branch"),("Updated",now.strftime("%b %Y"),"fa-calendar"),("Compat",compat,"fa-desktop"),("License",lt.capitalize(),"fa-scale-balanced"),("Author",creator,"fa-user")]')
FUNC.append('    sh = "".join([\'<div class="flex items-center gap-3 p-3 bg-black/30 rounded-xl border border-white/10"><div class="w-8 h-8 rounded-lg flex items-center justify-center text-xs text-purple-400 bg-purple-500/10"><i class="fas \' + si + \'"></i></div><div><div class="text-[10px] text-gray-500 uppercase">\' + sl + \'</div><div class="text-xs font-semibold text-white">\' + sv + \'</div></div></div>\' for sl,sv,si in sp])')
FUNC.append('    # Reviews')
FUNC.append('    rvs = get_reviews(product_id)')
FUNC.append('    st = get_rating_stats(product_id)')
FUNC.append('    ar = st[0] if st else rt')
FUNC.append('    tr = st[1] if st else rvc')
FUNC.append('    if rvs:')
FUNC.append('        rh = ""')
FUNC.append('        for r in rvs[:5]:')
FUNC.append('            rss = "".join([\'<i class="fas fa-star text-yellow-400 text-xs"></i>\' for _ in range(int(r.get("rating",5)))])')
FUNC.append('            rss += "".join([\'<i class="far fa-star text-gray-700 text-xs"></i>\' for _ in range(5-int(r.get("rating",5)))])')
FUNC.append('            rn = (r.get("author_name") or "Buyer")[:20]')
FUNC.append('            rt2 = (r.get("comment") or "Great product!")[:300]')
FUNC.append('            rh += \'<div class="bg-black/30 border border-white/10 rounded-xl p-4"><div class="flex items-center justify-between mb-2"><div class="flex items-center gap-2"><div class="w-8 h-8 rounded-full bg-gradient-to-br from-purple-500 to-pink-500 flex items-center justify-center text-[10px] font-bold text-white">\' + rn[0].upper() + \'</div><div><div class="text-xs font-semibold text-white">\' + rn + \'</div></div></div><div class="text-yellow-400">\' + rss + \'</div></div><p class="text-xs text-gray-400">\' + rt2 + \'</p></div>\'')
FUNC.append('    else:')
FUNC.append('        rh = \'<p class="text-sm text-gray-500 text-center py-4">No reviews yet.</p>\'')
FUNC.append('    # FAQ')
FUNC.append('    try: fi = _json.loads(faq_raw) if isinstance(faq_raw,str) and faq_raw.startswith("[") else []')
FUNC.append('    except: fi = []')
FUNC.append('    defaults = [{"q":"What is included?","a":"Items listed in What\\' + Q + "s Included."}')
FUNC.append('    while len(fi) < 10: fi.append(defaults[len(fi) % len(defaults)])')
FUNC.append('    fh = ""')
FUNC.append('    return "complete"')

with open('/root/voice-agent-manager/_hub_gen.py', 'w') as f:
    f.write('\n'.join(FUNC))
print('Generated ' + str(len(FUNC)) + ' lines')
